# Generated by Django 5.1.3 on 2024-12-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('announcement', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('photo_detail', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_announcement', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('beginning_activity', models.DateTimeField(blank=True, null=True)),
                ('seo_title', models.TextField(blank=True)),
                ('seo_description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
