# Generated by Django 5.1.3 on 2024-12-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='announcement',
            field=models.TextField(blank=True, null=True, verbose_name='Анонс'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='beginning_activity',
            field=models.DateField(blank=True, null=True, verbose_name='Начало активности'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Сортировка'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='photo_announcement',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото анонса'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='photo_detail',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Детальное фото'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='seo_description',
            field=models.TextField(blank=True, null=True, verbose_name='SEO DESCRIPTION'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='seo_title',
            field=models.TextField(blank=True, verbose_name='SEO TITLE'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True, verbose_name='Символьный код'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
